// Extracts the pure compute layer (functions, constants, column definitions and everything they
// depend on) from dashboard/app.js into one module, so the new app runs the SAME code as the
// classic site rather than a retyped copy. Usage: node extract.mjs <app.js> <out.ts>
import fs from "node:fs"
import * as acorn from "acorn"
import * as walk from "acorn-walk"

const [, , srcPath, outPath] = process.argv
const src = fs.readFileSync(srcPath, "utf8")
const ast = acorn.parse(src, { ecmaVersion: "latest", sourceType: "script", locations: true })

const DOM = new Set(["document", "window", "alert", "confirm", "prompt", "navigator", "indexedDB", "requestAnimationFrame", "MutationObserver", "IntersectionObserver", "Blob", "URL", "FileReader", "Image", "MediaRecorder", "AudioContext"])

// top-level declarations: name -> { node, kind }
const decls = new Map() // name -> index into items
const items = []
ast.body.forEach((node, i) => {
  const item = { node, names: [], idx: i }
  if (node.type === "FunctionDeclaration") item.names = [node.id.name]
  else if (node.type === "VariableDeclaration") {
    node.declarations.forEach((d) => {
      if (d.id.type === "Identifier") item.names.push(d.id.name)
      else if (d.id.type === "ObjectPattern" || d.id.type === "ArrayPattern") {
        walk.simple(d.id, { Identifier(n) { item.names.push(n.name) } })
      }
    })
  }
  items.push(item)
  item.names.forEach((n) => decls.set(n, item))
})

// Identifiers referenced anywhere inside a node (over-approximation: ignores shadowing).
function refs(node) {
  const out = new Set()
  walk.full(node, (n) => {
    if (n.type === "Identifier") out.add(n.name)
  })
  return out
}

const refCache = new Map()
const refsOf = (item) => {
  if (!refCache.has(item)) refCache.set(item, refs(item.node))
  return refCache.get(item)
}

// Entry points: every compute*/predict*/estimated*/format*/etc. function, plus every column list.
const entryNames = new Set()
items.forEach((it) => {
  const n = it.node
  if (n.type === "FunctionDeclaration") {
    if (/^(compute|predict|build|isQualifying|qualifyingGames|normalizeGame|recomputeDerivedStats|invalidateComputedCaches|getLeaderboard)/.test(n.id.name)) entryNames.add(n.id.name)
  } else if (n.type === "VariableDeclaration") {
    n.declarations.forEach((d) => {
      if (d.id.type === "Identifier" && /(_COLUMNS|_LABELS|_TYPES|_LEVELS|_MIN_|_THRESHOLD|COMPARISON_)/.test(d.id.name)) entryNames.add(d.id.name)
    })
  }
})
// the leaderboard row builder and a few helpers the UI calls directly
;["computeLeaderboard", "formatPct", "formatShootingSplit", "playerLink", "icon", "escapeHtml", "compareForSort"].forEach((n) => decls.has(n) && entryNames.add(n))

// DOM taint: an item is tainted if it references a DOM global, or references a tainted item.
const tainted = new Set()
{
  let grew = true
  while (grew) {
    grew = false
    items.forEach((it) => {
      if (tainted.has(it)) return
      const r = refsOf(it)
      if ([...r].some((x) => DOM.has(x)) || [...r].some((x) => decls.has(x) && tainted.has(decls.get(x)) && decls.get(x) !== it)) {
        tainted.add(it)
        grew = true
      }
    })
  }
}

// closure
const included = new Set()
const queue = []
const addName = (name) => {
  const it = decls.get(name)
  if (it && !included.has(it)) {
    included.add(it)
    queue.push(it)
  }
}
entryNames.forEach(addName)
// DOM-free top-level statements that touch included names (initializers like X.forEach(...))
const STMT_TYPES = new Set(["ExpressionStatement"])
let changed = true
while (changed) {
  changed = false
  while (queue.length) {
    const it = queue.pop()
    refsOf(it).forEach(addName)
  }
  items.forEach((it) => {
    if (included.has(it) || !STMT_TYPES.has(it.node.type)) return
    const r = refsOf(it)
    if ([...r].some((x) => DOM.has(x))) return
    if (tainted.has(it)) return
    // only initializer-style statements: they must mutate (not merely read) an included name
    const touches = [...r].some((x) => decls.has(x) && included.has(decls.get(x)))
    const allKnown = [...r].every((x) => !decls.has(x) || true)
    if (touches && allKnown && it.node.expression.type !== "AwaitExpression") {
      included.add(it)
      queue.push(it)
      changed = true
    }
  })
}

// state handling
const overrideState = decls.get("state")
const loadStateItem = decls.get("loadState")
included.delete(loadStateItem)
included.delete(decls.get("saveState"))
if (overrideState) included.delete(overrideState)

const chunks = []
for (const it of items) {
  if (!included.has(it)) continue
  let text = src.slice(it.node.start, it.node.end)
  // `let x = localStorage...` toggles keep working in the browser; no rewrite needed.
  chunks.push(text)
}

const header = `// @ts-nocheck
// GENERATED by extract.mjs from dashboard/app.js -- do not edit by hand. The compute layer, column
// definitions and their dependencies, extracted verbatim so the numbers match the classic site
// exactly. Regenerate with: node extract.mjs ../dashboard/app.js src/lib/legacy-core.ts
let state = { players: [], games: [], masterVideos: [], rsvps: [], seasonHistory: [], currentSeasonStartedAt: null, playerPhysicalOverrides: {} };
function saveState() {}
export function setLegacyState(s) { state = s; invalidateComputedCaches(); }
export function setLegacyToggles(t) {
  if (t.imbalanced !== undefined) includeImbalancedGames = t.imbalanced;
  if (t.pastSeasons !== undefined) includePastSeasons = t.pastSeasons;
  if (t.outliers !== undefined) includeOutlierGames = t.outliers;
  invalidateComputedCaches();
}
export function normalizeLegacyState(s) {
  s.masterVideos = s.masterVideos || [];
  s.masterVideos.forEach(m => { if (m.fileName === undefined) m.fileName = null; });
  (s.games || []).forEach(normalizeGame);
  s.seasonHistory = s.seasonHistory || [];
  s.currentSeasonStartedAt = s.currentSeasonStartedAt || null;
  s.playerPhysicalOverrides = s.playerPhysicalOverrides || {};
  s.rsvps = s.rsvps || [];
  return s;
}
`

// export every top-level function and const that is an entry or referenced externally by name
const exportNames = [...included].flatMap((it) => it.names)
const footer = `\nexport { ${[...new Set(exportNames)].join(", ")} };\n`

fs.writeFileSync(outPath, header + "\n" + chunks.join("\n\n") + footer)
console.log(`extracted ${chunks.length} top-level items, ${exportNames.length} names, ${(fs.statSync(outPath).size / 1024).toFixed(0)} KB`)
const missing = []
included.forEach((it) => refsOf(it).forEach((r) => { if (decls.has(r) && !included.has(decls.get(r))) missing.push(r) }))
console.log("included expression statements:", items.filter((it) => included.has(it) && it.node.type === "ExpressionStatement").map((it) => src.slice(it.node.start, it.node.start + 70).replace(/\s+/g, " ")))
console.log("excluded-but-referenced:", [...new Set(missing)].slice(0, 40).join(", "))
